### ISSUE TITLE
Upgrade libhoudini

### ISSUE THREAD

**Issue by chenxiex** [casualsnek/waydroid_script#59]
I want to upgrade libhoudini. Should I do something to uninstall the old libhoudini and install the new one, or I can just install the new one and the script will take care of this?

**Comment by LegacyGamerHD** [comment]
try https://github.com/LegacyGamerHD/waydroid_script

**Comment by LegacyGamerHD** [comment]
its more uptodate

**Comment by chenxiex** [comment]
> try https://github.com/LegacyGamerHD/waydroid_script

This is a great repo. But how can I switch to this? Should I do something to uninstall the old libhoudini and install the new one, or I can just install the new one and the script will take care of this?

**Comment by tutacat** [comment]
> > try https://github.com/LegacyGamerHD/waydroid_script
> This is a great repo. But how can I switch to this?

When you install the new files, it will overwrite (replace, like it was deleted) the existing files because its the same software. Hopefully all of them.

If you encounter an error after running the new install command, you may need to delete the old files, _after_ running _this_ (old) installer AGAIN, then remove them using the tree found in /tmp//tmp/houdiniunpack/vendor_*/prebuilts/

Which you could do, as example, using the following

    (
        cd /tmp/houdini/vendor_*/prebuilts/;
        find -type f;
    ) | while read path; do
        sudo rm /var/lib/waydroid/overlay/system/"$path";
    done
